---
language: python


matrix:
  include:
    - os: linux
      dist: trusty
      python: "2.7"
      sudo: required
    - os: linux
      dist: precise
      python: "2.7"
      sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip


script:
  - python --version
  - python code.py

