---
language: python
python: "2.7"

dist: trusty
dist: precise
sudo: required


# Install ansible
addons:
  apt:
    packages:
    - python-pip


script:
  - python code.py
  - python --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
