---
language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: "2.7"
    - os: linux
      dist: precise
      sudo: required
      python: "2.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

script:
  - python --version
  - python code.py

