---
language: python
python: "2.7"

sudo: required
env:
  - distro: ubuntu
    version: 12.04
  - distro: ubuntu
    version: 14.04
  - distro: centos
    version: 7


# Install ansible
addons:
  apt:
    packages:
    - python-pip


script:
  - python --version
  - python code.py

