---
language: python
python: "2.7"
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise

# Install ansible
addons:
  apt:
    packages:
    - python-pip

script:
  - python --version
  - python code.py

